apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: git@github.com:prai05/idp-app.git
    targetRevision: main
    path: platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true