apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:prai05/nonprod-k8s-manifests.git  
    targetRevision: main  
    path: dev/demo-app/cart
    
  destination:
    server: https://kubernetes.default.svc
    namespace: cart
  syncPolicy: 
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true